### ISSUE TITLE
license:remove is not working

### ISSUE THREAD

**Issue by masih** [mycila/license-maven-plugin#41]
The `remove` goal does not remove file headers despite the log messages saying the headers are removed.

My plugin configuration: 

``` xml
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>2.5</version>
    <configuration>
        <header>com/mycila/maven/plugin/license/templates/GPL-3.txt</header>
        <excludes>
            <exclude>**/README</exclude>
            <exclude>src/test/resources/**</exclude>
            <exclude>src/main/resources/**</exclude>
        </excludes>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

The command I execute is `mvn license:remove`.

The (shortened) log:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building XXX 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- license-maven-plugin:2.5:remove (default-cli) @ XXX ---
[INFO] Removing license headers...
[INFO] Removing license header from: XXXXXX.java
.
.
.
[INFO] Removing license header from: XXXXXX.java

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.379 s
[INFO] Finished at: 2014-06-09T14:11:58+00:00
[INFO] Final Memory: 9M/182M
[INFO] ------------------------------------------------------------------------
```

I have enabled `-X` and no exceptions are being thrown by the plugin.
Any clues?

Many thanks

**Comment by mathieucarbou** [comment]
Please provide a junit test to reproduce. Or provide a pull request.

**Comment by McFoggy** [comment]
I succeed in reproducing the issue under a branch of [my fork](https://github.com/McFoggy/license-maven-plugin/tree/issue-41).

Basically actions to reproduce:
- from a file without header
- using `format` goal add GPL-3.txt header 
- call remove goal

A user could expect that the header is removed, I was such a guy until I discovered the keywords parameter on the mojo.
By default, it contains only the word "copyright", that is not part of GPL-3 header.

If we change that keywords list to match something that is inside the GPL-3 license then the removal occures.

This is obviously error prone for the end users.

What could be done (to be discussed/evaluate):
1) warn or error when the end users add a license that do not contain the expected keywords
or
2) suppress the checks on keywords. Here I do not evaluate all what that would imply and what could be the consequences. I even do not fully understand the purpose of those keywords. @mathieucarbou can you explain why keywords are there?

**Comment by juandesi** [comment]
Still facing this issue... is there someone working on this?

```[INFO]
[INFO] --- license-maven-plugin:2.11:remove (default-cli) @ tressietecero-connector ---
[INFO] Removing license headers...
[INFO] Removing license header from: /Users/XXX/File.java
[INFO] Removing license header from: /Users/XXX/File2.java
[INFO] Removing license header from: /Users/XXX/File3.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.998 s```

its been more than a year

**Comment by mathieucarbou** [comment]
Sadly I have no time now to fix it - If someone could provide a pull requets I would be pleased to apply it.
Thanks!

**Comment by juandesi** [comment]
Thanks for replying Mathieu, I'll try to make some time to provide a PR.

**Comment by McFoggy** [comment]
I think the test is not the problem, I described how to reproduce and a test is waiting in [a branch](https://github.com/McFoggy/license-maven-plugin/tree/issue-41). Instead @mathieucarbou can you try to answer the questions I asked concerning the keywords for this issue? Once it is decided what to do it will be easier to do it ;-)

**Comment by mathieucarbou** [comment]
Sorry @McFoggy I completely missed the previous discussions...

Actually, as I remember, the first implementation of the plugin didn't contain any pattern matching capabilities for detecting starting, ending and lines part of a header. Header detection was done in the first version through keywords.

Then, when the plugin added the header detection feature by using patterns, the keywords were kept at their simple possible form, but were configurable. This was done like this because a lot of license headers are using the same comment syntax as standard comments in the source code, so this was done in order to detect if the comment block matching the license header pattern is a license of a mere comment.

The other reason why the keyword set must be kept as minimal as possible is that the licensing of source files could eventually change. So the plugin should be able to detect that a comment block is or is not a header, and if it is, replace it by the license. Thus, we cannot base the header detection on words in the `wanted` license to check for and update to.

I completely agree that this design is error-prone. It is based first on pattern matching and then on word detection so there could be false positives. But it works so far for the majority of cases and even more if people configure the `keyword` parameter used to detect a header (i.e. javadoc http://code.mycila.com/license-maven-plugin/reports/2.3/remove-mojo.html)

As a proof, if you currently put in a file a comment which contains the word copyright, and which is not a license header, then this comment could be removed when calling the remove task :-( In Java, I don't any case where it should be an issue. But on groovy scripts for example or some other languages, this behavior could hurt more.

So given this explanation, a way to get rid of keywords would be to add some intelligence which is able to detect if a comment block is actually a header, but without considering the configured license that we must check against or update to. When we remove, the license parameter is not used so anyway it is useless ;-)

And this is where it is complicated: how could you determine that a comment block is really a license block, event in cases when license files are used inside corporate with really custom-made licenses. So that's why we just stood with keyword detection using `copyright`.

__back to the issue__

For this case, the issue is that the GPL 3 header has not been correctly stated:

From http://www.gnu.org/licenses/gpl-3.0.html, it should read:

```
     This file is part of ${project.name}.
     Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

whereas the plugin template is:

```
This file is part of ${project.name}.

${project.name} is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

${project.name} is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with ${project.name}.  If not, see <http://www.gnu.org/licenses/>.
```

I think the guy which contributed this license header customized it a bit too far ;-) Probably a review of all included templates in the plugin would be better to:

1. make sure the word copyright is there (often, license contains thsi word)
2. make sure the templates correctly match the official version.

For GPL 3, we should remove the two ${project.name} placeholders in the text block (not the one in the first line which is the comment line), and add the year and eventually owner (or author ?) placeholder

Mathieu.

**Comment by sebhoss** [comment]
Oh yeah that was me :-( 

I felt that using something like `${project.inceptionYear}` for the copyright year is not correct (at least not beyond the inception year) and adding things like `${owner}` or `${email}` to the template would make it harder for users to use the plugin. I did not know about the copyright keyword back then, so i blindly removed the first line from the GPL templates.

I've pushed a [small change](https://github.com/mycila/license-maven-plugin/compare/master...sebhoss:issue-41) ([commit](https://github.com/sebhoss/license-maven-plugin/commit/cec65c0dff351eae69c0928759326fd238731557)) for the templates to fix this.

WRT removing/updating existing headers from projects that used the broken templates before: Change the keyword to `GPL` and re-run the goal.

@mathieucarbou do you actually want to work on replacing this keyword based approach with something else? Might have a little time in the next few weeks to help out here :-)

**Comment by mathieucarbou** [comment]
Integrated in Pr #101 - will try to also integrate PR #80 from @McFoggy
