### ISSUE TITLE
Copyright years based on git history

### ISSUE THREAD

**Issue by ppalaga** [mycila/license-maven-plugin#54]
We have recently introduced a custom PropertiesProvider in [our project](https://github.com/hawkular/hawkular-build-tools/blob/master/src/main/java/org/hawkular/build/license/CopyrightRangeProvider.java#L41)  that adds two new properties:

* `license.copyrightLastYear` - the year of the last change of the present file as seen in git history
* `license.copyrightYears` - the combination of `project.inceptionYear` and `license.copyrightLastYear` delimited by a dash, or just `project.inceptionYear` if `project.inceptionYear` is eqal to `license.copyrightLastYear`

In this way we are able to comply with the requirement of our legal department to update the copyright range anytime the given file is changed without too much manual work. Because this kind of requirement is certainly quite common, we are looking for a way to share our code.

To contribute our code to license plugin seems to be the first natural choice. However our code depends on jGit and you probabaly will not be wanting to introduce the jGit dependency to license plugin itself. 
Maybe a submodule of license plugin would be better? That submodule would build to a jar that could optionally be used by license plugin at runtime. WDYT?

**Comment by mathieucarbou** [comment]
Understood!

I think of 2 ways implementing this in MLP:

In exemple in MLP configuration you can currently set properties like this:

<properties>
    <owner>Mycila</owner>
    <email>mathieu.carbou@gmail.com</email>
</properties>

an idea would be to introduce a propertiesProvider setting:

<propertiesProviderClasses>
    <propertiesProviderClass>org.hawkular.build.license.CopyrightRangeProvider</propertiesProviderClass>
</propertiesProviderClasseses>

So we could have such behavior:

1. MLP laods proeprties like it it currently done (which handle the properties section)
2. Then find if a propertiesProviderClass class is available, and if yes, instantiate it and gets the properties (which overrides existing ones)

Another solution would be to use the JDK ServiceLoader system to load all implementations of an interface from the classpath. This way, several implementations could provided their own properties (and could be several properties provider).

This way the properties provider could just be an interface:

public interface PropertiesProvider {
Map<String, String> getAdditionalProperties(AbstractLicenseMojo mojo, Properties properties,
            Document document) {
}

in the MLP project.

Then in your project you just implement it and provide either a configuration, or a META-INF/services/com.mycila...PropertiesProvider file referring to all your PropertiesProvider implementations.

ServiceLoader pros:
* it enables several providers through plugins, projects, etc.. to be discovered automatically. Thus, it could avoid any configuration complexity. You could put the GIT class in a simple JAR and add this jar as a dependency of MLP plugin and the property provider will be automatically discovered

ServiceLoader cons:
* unwanted properties could come from plugins or unwanted jars in project having such META-INF/services file
* no guaranteed order of providers (=> no override order)

<propertiesProviderClass> pros: 
* better control over properties from a project / module and can also specify several providers, in order

<propertiesProviderClass> cons: 
* harder to use plugins architecture  (i.e. having a plugin jar set to MLP to automatically loads properties from git) since you have to declare your provider in the config

Let me know what you think of! 

This way you could easily provider a little modification in your fork and send a pull request I think.

Thanks :+1: 

Mat'

**Comment by ppalaga** [comment]
I do not know if I stated explicitly enough that we already have an implementation of `com.mycila.maven.plugin.license.PropertiesProvider` here: https://github.com/hawkular/hawkular-build-tools/blob/master/src/main/java/org/hawkular/build/license/CopyrightRangeProvider.java#L70
It works quite well with the ServiceLoader framework and I am OK to leave it like that.

As you seem to imply that this functionality is welcome I am going to prepare a PR with how I'd introduce it to your source tree.

**Comment by mathieucarbou** [comment]
Thanks :-)

**Comment by mathieucarbou** [comment]
Merged #56
