### ISSUE TITLE
tests are failing on windows

### ISSUE THREAD

**Issue by McFoggy** [mycila/license-maven-plugin#70]
On windows some tests are failing as exemple RemoveMojoTest#test_remove_script_style.

The errors are mainly because loaded files contain `\r\n` whereas the test itself checks against `\n`.
Of course changing the tested string to `r\n` corrects the behavior, but why the hell is it working under linux boxes of travis-ci?

**Comment by McFoggy** [comment]
difference might come from git checkout and core.autocrlf setting.
if tests are really relying on end lines, isn't there the need of defining a git [repository settings file](https://help.github.com/articles/dealing-with-line-endings/)

**Comment by McFoggy** [comment]
investigating further I think that line ending should be reworked in the project, there is no consistency all over the project depending on file input content, example: 
in FileContent#FileContent() there is a false assertion i guess: `unix = fileContent.indexOf("\r") == -1` which is probably wrong for one line files under windows.

@mathieucarbou : what was your intention in the project regarding EOL for files in which the plugin performs modifications? keep them as they are except where you introduce the header ? use platform EOL for all touched files?

**Comment by mathieucarbou** [comment]
Hi

I am using Windows at home also and all releases of the plugins and tests are run on Windows before releasing. I also have an Ubuntu laptop and  lot of contributors are using Ubuntu. The Travis continuous build of the project also runs on Linux. And it pass. All tests passed for the latest release. As you can see, here are the modifications in the project since the latest release:

https://github.com/mycila/license-maven-plugin/compare/4290c6729b871b24672ade38c788071808cc3fc6...master

I am not sure that these modifications impact the tests.

As for the `autocrlf` setting of GIT, I suggest you use `core.autocrlf = false`. The main reason is that you do not want GIT to modify any files of your project by its own. All IDEs already have settings to define which EOL to use for files. So anyway, whether you are usng win or lin, your IDE should always produce the same EOL. And it is too dangerous to allo GIT to change the project files!

If there were such big issue in the project concerning EOL, I think it would have been reported and fixed  long while ago and contributors would have pointed out already the issue

The goal of the project is to keep when inserting the header the same EOL which exists in the file. So there is a detection that is performed to check for \r in the file we want to insert the header into. The project does not rely at all on the running platform to be consistent.

`unix = fileContent.indexOf("\r") == -1`

I agree that a one-line file in Windows will treat this file as a unix one. But this o for consistency, we do not want to check the running platform to change this behavior because it would'n be consistent.

Anyway...

If you have some pull request to provide to improve these parts of the project they are very welcomed :-)

**Comment by McFoggy** [comment]
yes on my windows machine I have `core.autocrlf = true`, which is unfortunately or not part of a lot of GIT documentations ([GIT SCM book](http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration), [Github documentation](https://help.github.com/articles/dealing-with-line-endings/)).

> I understand & agree with the goal of the project that is to use the same EOL which already exist in a file

having said that several choices pop up:

1. consider that everyone will have `core.autocrlf` set to `false`
2. provide repository settings via a .gitattributes file
3. make the tests independent from EOL constants

After those choices the question remains for one line source file. Which EOL should be used? a fixed one? the platform one?

Personally I'd vote for the choice (3) and would suggest to default to platform EOL for one line files.

What do you think?

**Comment by mathieucarbou** [comment]
Using platform EOL is inconsistent because of win/unix diferences. So using platform EOL for one-line files is not a solution. When you work in a big team where people are using different systems, this is something you have to consider. The choice in the plugin is thus to use the unix behavior by default, which has less impacts because IDEs and even windows handles that.

That being said, for a lot of  projects, perhaps all these settings won't make a difference. But this project deals with file formatting and tests and has and SHOULD (as I remember) contain files formated differently for the tests.

So converting project files to either CRLF or LF is not an option.

All source files should remain in their exact state.
